name: "Check & Cachix"
on:
  push:
    branches:
      - main
      - trying
      - staging
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.7.0pre20220209_52f5231/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          extra-platforms = x86_64-darwin i686-linux aarch64-linux
          substituters = https://wantondanny.cachix.org https://nrdxp.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = wantondanny.cachix.org-1:9LABQFsKi2DBRtFiSnqfsVFgTsc65l3hHrphFbrefcA= nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - uses: cachix/cachix-action@v10
      with:
        name: wantondanny
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix -Lv flake check --show-trace --keep-going
    - run: nix -Lv build ".#nixosConfigurations.NixOS.config.system.build.toplevel"
    - run: nix -Lv develop -c echo OK